name: first-action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  start:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Print my initials
        run: |
          sudo chmod 777 script.sh
          ./script.sh
